/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.mycompany.projetoindividual;

import java.util.concurrent.ThreadLocalRandom;

/**
 *
 * @author T-GAMER
 */
public class Aplicacao extends javax.swing.JFrame {

    public Aplicacao() {
        initComponents();
    }
    Integer randomCPU, randomDisco, randomMem;

    Integer CPUmax = 0;
    Integer Discomax = 0;
    Integer Memmax = 0;

    Integer CPUmin = 100;
    Integer Discomin = 100;
    Integer Memmin = 100;

    Double totalCPU = 0.0;
    Double totalDisco = 0.0;
    Double totalMem = 0.0;
    
    Double mediaCPU, mediaDisco, mediaMem;

    Double count = 0.0;

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        pgbDisco = new javax.swing.JProgressBar();
        pgbCPU = new javax.swing.JProgressBar();
        pgbMem = new javax.swing.JProgressBar();
        lblCPU = new javax.swing.JLabel();
        lblDisco = new javax.swing.JLabel();
        lblMem = new javax.swing.JLabel();
        btnGerar = new javax.swing.JButton();
        lblCPUmax = new javax.swing.JLabel();
        lblCPUmin = new javax.swing.JLabel();
        lblCPUmedia = new javax.swing.JLabel();
        lblDiscomax = new javax.swing.JLabel();
        lblDiscomin = new javax.swing.JLabel();
        lblDiscomedia = new javax.swing.JLabel();
        lblMemmax = new javax.swing.JLabel();
        lblMemmin = new javax.swing.JLabel();
        lblMemmedia = new javax.swing.JLabel();
        resCPUmax = new javax.swing.JLabel();
        resCPUmin = new javax.swing.JLabel();
        resCPUmedia = new javax.swing.JLabel();
        resDiscomax = new javax.swing.JLabel();
        resDiscomin = new javax.swing.JLabel();
        resDiscomedia = new javax.swing.JLabel();
        resMemmax = new javax.swing.JLabel();
        resMemmin = new javax.swing.JLabel();
        resMemmedia = new javax.swing.JLabel();
        lblCreditos = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("DialogInput", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 0, 0));
        jLabel1.setText("Seu Computador!");

        pgbDisco.setStringPainted(true);

        pgbCPU.setStringPainted(true);

        pgbMem.setStringPainted(true);

        lblCPU.setFont(new java.awt.Font("DialogInput", 1, 18)); // NOI18N
        lblCPU.setForeground(new java.awt.Color(0, 0, 153));
        lblCPU.setText("CPU");

        lblDisco.setFont(new java.awt.Font("DialogInput", 1, 18)); // NOI18N
        lblDisco.setForeground(new java.awt.Color(33, 71, 249));
        lblDisco.setText("Disco");

        lblMem.setFont(new java.awt.Font("DialogInput", 1, 18)); // NOI18N
        lblMem.setForeground(new java.awt.Color(17, 131, 187));
        lblMem.setText("Memória");

        btnGerar.setBackground(new java.awt.Color(255, 255, 255));
        btnGerar.setFont(new java.awt.Font("DialogInput", 1, 15)); // NOI18N
        btnGerar.setForeground(new java.awt.Color(0, 0, 0));
        btnGerar.setText("Fazer leitura dos dados");
        btnGerar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGerarActionPerformed(evt);
            }
        });

        lblCPUmax.setText("Máximo :");

        lblCPUmin.setText("Mínimo :");

        lblCPUmedia.setText("Média :");

        lblDiscomax.setText("Máximo :");

        lblDiscomin.setText("Mínimo :");

        lblDiscomedia.setText("Média :");

        lblMemmax.setText("Máximo :");

        lblMemmin.setText("Mínimo :");

        lblMemmedia.setText("Média :");

        resCPUmax.setText("?");

        resCPUmin.setText("?");

        resCPUmedia.setText("?");

        resDiscomax.setText("?");

        resDiscomin.setText("?");

        resDiscomedia.setText("?");

        resMemmax.setText("?");

        resMemmin.setText("?");

        resMemmedia.setText("?");

        lblCreditos.setFont(new java.awt.Font("DialogInput", 1, 12)); // NOI18N
        lblCreditos.setForeground(new java.awt.Color(0, 0, 0));
        lblCreditos.setText("Amanda Caramico - 02211001");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(72, 72, 72)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(lblCPUmedia)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(resCPUmedia))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(lblCPUmin)
                                        .addGap(18, 18, 18)
                                        .addComponent(resCPUmin)))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(pgbCPU, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(lblCPU)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(lblCPUmax)
                                        .addGap(18, 18, 18)
                                        .addComponent(resCPUmax)))
                                .addGap(63, 63, 63)))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(pgbDisco, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblDisco)
                            .addComponent(jLabel1)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(lblDiscomedia)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(resDiscomedia))
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                    .addComponent(lblDiscomin)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(resDiscomin))
                                .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                    .addComponent(lblDiscomax)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                    .addComponent(resDiscomax))))
                        .addGap(73, 73, 73)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(lblMemmin)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(resMemmin))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(lblMemmax)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(resMemmax))
                            .addComponent(lblMem)
                            .addComponent(pgbMem, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(lblMemmedia)
                                .addGap(18, 18, 18)
                                .addComponent(resMemmedia))))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 224, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(btnGerar)
                        .addGap(231, 231, 231)))
                .addGap(68, 68, 68))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblCreditos)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addComponent(jLabel1)
                .addGap(28, 28, 28)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(lblDisco)
                    .addComponent(lblCPU, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblMem))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(pgbMem, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(pgbDisco, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(pgbCPU, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblCPUmax)
                    .addComponent(lblDiscomax)
                    .addComponent(lblMemmax)
                    .addComponent(resCPUmax, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(resDiscomax, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(resMemmax, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblCPUmin)
                    .addComponent(lblDiscomin)
                    .addComponent(lblMemmin)
                    .addComponent(resCPUmin, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(resDiscomin, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(resMemmin))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblCPUmedia)
                    .addComponent(lblDiscomedia)
                    .addComponent(lblMemmedia)
                    .addComponent(resCPUmedia, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(resDiscomedia, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(resMemmedia, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 60, Short.MAX_VALUE)
                .addComponent(btnGerar)
                .addGap(23, 23, 23)
                .addComponent(lblCreditos)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnGerarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGerarActionPerformed
        randomCPU = ThreadLocalRandom.current().nextInt(0, 101);
        randomDisco = ThreadLocalRandom.current().nextInt(0, 101);
        randomMem = ThreadLocalRandom.current().nextInt(0, 101);

        pgbCPU.setValue(randomCPU);
        pgbDisco.setValue(randomDisco);
        pgbMem.setValue(randomMem);

        if (count.equals(0.0)) {
            CPUmax = randomCPU;
            resCPUmax.setText(CPUmax + "%");
            CPUmin = randomCPU;
            resCPUmin.setText(CPUmin + "%");

            Discomax = randomDisco;
            resDiscomax.setText(Discomax + "%");
            Discomin = randomDisco;
            resDiscomin.setText(Discomin + "%");

            Memmax = randomMem;
            resMemmax.setText(Memmax + "%");
            Memmin = randomMem;
            resMemmin.setText(Memmin + "%");
        } else {

            if (randomCPU > CPUmax) {
                CPUmax = randomCPU;
                resCPUmax.setText(CPUmax + "%");
            } else if (randomCPU < CPUmin) {
                CPUmin = randomCPU;
                resCPUmin.setText(CPUmin + "%");
            }
            if (randomDisco > Discomax) {
                Discomax = randomDisco;
                resDiscomax.setText(Discomax + "%");
            } else if (randomDisco < Discomin) {
                Discomin = randomDisco;
                resDiscomin.setText(Discomin + "%");
            }
            if (randomMem > Memmax) {
                Memmax = randomMem;
                resMemmax.setText(Memmax + "%");
            } else if (randomMem < Memmin) {
                Memmin = randomMem;
                resMemmin.setText(Memmin + "%");
            }
        }
        count++;

        totalCPU += randomCPU;
        totalDisco += randomDisco;
        totalMem += randomMem;

        mediaCPU = totalCPU / count;
        mediaDisco = totalDisco / count;
        mediaMem = totalMem / count;

        resCPUmedia.setText(String.format("%.2f", mediaCPU)+"%");
        resDiscomedia.setText(String.format("%.2f", mediaDisco)+"%");
        resMemmedia.setText(String.format("%.2f", mediaMem)+"%");
        
    }//GEN-LAST:event_btnGerarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Aplicacao.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Aplicacao.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Aplicacao.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Aplicacao.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Aplicacao().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnGerar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel lblCPU;
    private javax.swing.JLabel lblCPUmax;
    private javax.swing.JLabel lblCPUmedia;
    private javax.swing.JLabel lblCPUmin;
    private javax.swing.JLabel lblCreditos;
    private javax.swing.JLabel lblDisco;
    private javax.swing.JLabel lblDiscomax;
    private javax.swing.JLabel lblDiscomedia;
    private javax.swing.JLabel lblDiscomin;
    private javax.swing.JLabel lblMem;
    private javax.swing.JLabel lblMemmax;
    private javax.swing.JLabel lblMemmedia;
    private javax.swing.JLabel lblMemmin;
    private javax.swing.JProgressBar pgbCPU;
    private javax.swing.JProgressBar pgbDisco;
    private javax.swing.JProgressBar pgbMem;
    private javax.swing.JLabel resCPUmax;
    private javax.swing.JLabel resCPUmedia;
    private javax.swing.JLabel resCPUmin;
    private javax.swing.JLabel resDiscomax;
    private javax.swing.JLabel resDiscomedia;
    private javax.swing.JLabel resDiscomin;
    private javax.swing.JLabel resMemmax;
    private javax.swing.JLabel resMemmedia;
    private javax.swing.JLabel resMemmin;
    // End of variables declaration//GEN-END:variables
}
